Repository S0YKIM/Cub3d, pull requests merged in 2022-09, with the labels that each got.

#33 refactor: Refactoring free_all() function
  srcs/exit/exit.c
  srcs/main.c
Labels: refactoring :+1:

#34 fix: Fix double free error in free_all()
  includes/cub3d.h
  includes/struct.h
  libs/libft/ft_strjoin_free.c
  srcs/exit/exit.c
  srcs/init/init.c
  srcs/main.c
  srcs/map/identifier.c
  srcs/map/map.c
  srcs/map/wall.c
Labels: bug :lady_beetle:, refactoring :+1:

#35 fix: Fix bug which recognized player outside map was okay (#30)
  srcs/map/check.c
  srcs/map/map.c
Labels: bug :lady_beetle:

#38 feat: Implement function to open new window and terminate the program
  Makefile
  includes/cub3d.h
  includes/macro.h
  includes/struct.h
  srcs/init/init.c
  srcs/main.c
  srcs/mlx/exit.c
Labels: feature :star:

#39 feat: Implement function to quit the program when esc key is pressed (#37)
  Makefile
  includes/cub3d.h
  includes/macro.h
  srcs/main.c
  srcs/mlx/keyhook.c
Labels: feature :star:

#41 feat: Implement function to rotate direction and plane vector by rotation matrix (#40)
  Makefile
  includes/cub3d.h
  includes/struct.h
  srcs/init/init.c
  srcs/map/map.c
  srcs/math/rotate.c
Labels: feature :star:

#42 feat: Add 0.5 to player's initial position (#40)
  includes/macro.h
  includes/struct.h
  srcs/map/map.c
  srcs/mlx/keyhook.c
Labels: feature :star:

#43 feat: Implement function to set player's position after checking if movement is available (#40)
  Makefile
  includes/cub3d.h
  includes/struct.h
  srcs/main.c
  srcs/map/player.c
  srcs/math/rotate.c
  srcs/mlx/keyhook.c
Labels: feature :star:

#44 feat: Implement function to draw frame
  Makefile
  includes/cub3d.h
  includes/struct.h
  srcs/exit/exit.c
  srcs/init/init.c
  srcs/main.c
  srcs/mlx/draw.c
  srcs/mlx/exit.c
Labels: feature :star:

#46 feat: Implement draw_wall() and calculate perpendicular distance (#45)
  Makefile
  includes/cub3d.h
  includes/macro.h
  includes/struct.h
  srcs/dda/hit.c
  srcs/dda/line.c
  srcs/dda/perp.c
  srcs/dda/set.c
  srcs/exit/mlx.c
  srcs/exit/program.c
  srcs/init/info.c
  srcs/mlx/draw.c
Labels: feature :star:

#47 feat: Implement draw_line() and fix error (#45)
  Makefile
  maps/map.cub
  srcs/dda/hit.c
  srcs/mlx/draw.c
Labels: feature :star:

#50 fix: Fix bug which player did not move or rotate even if key was pressed
  includes/cub3d.h
  includes/macro.h
  srcs/main.c
  srcs/map/player.c
  srcs/mlx/draw.c
  srcs/mlx/keyhook.c
Labels: bug :lady_beetle:

#51 fix: Let player available to move when next position is in the same tile where present position is (#40)
  maps/mini.cub
  srcs/dda/set.c
  srcs/map/player.c
Labels: bug :lady_beetle:

#53 fix: Fix calc_rotated_vector() (#52)
  srcs/math/rotate.c
Labels: bug :lady_beetle:

#54 fix: Fix bug which player moved backward when 'W' key was pressed (#52) (#7)
  maps/map.cub
  srcs/init/info.c
Labels: bug :lady_beetle:

#56 add: Upload texture files (#55)
  textures/texture1.xpm
  textures/texture2.xpm
  textures/texture3.xpm
  textures/texture4.xpm
Labels: etc :guitar:

#59 feat: Implement functions to calculate variables needed for textured rendering
  Makefile
  README.md
  includes/cub3d.h
  includes/macro.h
  includes/struct.h
  srcs/dda/line.c
  srcs/exit/mlx.c
  srcs/mlx/draw.c
  srcs/mlx/texture.c
Labels: bug :lady_beetle:, feature :star:

#61 fix: Fix wall rendering error
  srcs/mlx/texture.c
Labels: bug :lady_beetle:

#63 feat: Implement function to draw minimap (#62)
  Makefile
  includes/cub3d_bonus.h
  includes/macro_bonus.h
  includes/struct_bonus.h
  srcs_bonus/dda/hit_bonus.c
  srcs_bonus/dda/line_bonus.c
  srcs_bonus/dda/perp_bonus.c
  srcs_bonus/dda/set_bonus.c
  srcs_bonus/exit/mlx_bonus.c
  srcs_bonus/exit/program_bonus.c
  srcs_bonus/init/info_bonus.c
  srcs_bonus/init/texture_bonus.c
  srcs_bonus/main_bonus.c
  srcs_bonus/map/check_bonus.c
  srcs_bonus/map/identifier_bonus.c
  srcs_bonus/map/map_bonus.c
  srcs_bonus/map/player_bonus.c
  srcs_bonus/map/wall_bonus.c
  srcs_bonus/math/rotate_bonus.c
  srcs_bonus/mlx/draw_bonus.c
  srcs_bonus/mlx/keyhook_bonus.c
  srcs_bonus/mlx/minimap_bonus.c
  srcs_bonus/mlx/texture_bonus.c
Labels: feature :star:

#64 fix: Fix norminette errors (#24)
  includes/cub3d.h
  includes/cub3d_bonus.h
  includes/struct.h
  includes/struct_bonus.h
  srcs/init/info.c
  srcs/init/texture.c
  srcs/math/rotate.c
  srcs/mlx/draw.c
  srcs/mlx/keyhook.c
  srcs/mlx/texture.c
  srcs_bonus/init/info_bonus.c
  srcs_bonus/init/texture_bonus.c
  srcs_bonus/math/rotate_bonus.c
  srcs_bonus/mlx/draw_bonus.c
  srcs_bonus/mlx/keyhook_bonus.c
  srcs_bonus/mlx/minimap_bonus.c
  srcs_bonus/mlx/texture_bonus.c
Labels: refactoring :+1:

#65 fix: Fix norm errors (#24)
  includes/cub3d_bonus.h
  includes/macro_bonus.h
  includes/struct_bonus.h
Labels: etc :guitar:

#67 fix: Fix error in case map contains undefined letter (#58)
  srcs/map/check.c
  srcs/map/identifier.c
Labels: bug :lady_beetle:

#70 fix: Fix error with incomplete rgb color (#69) (#58)
  includes/macro.h
  maps/map.cub
  maps/mini.cub
  maps/tiny.cub
  srcs/map/check.c
  srcs/map/identifier.c
  srcs_bonus/map/check_bonus.c
  srcs_bonus/map/identifier_bonus.c
Labels: bug :lady_beetle:

#71 fix: Fix header file included (#3)
  includes/cub3d_bonus.h
Labels: etc :guitar:

#73 Merge hotfix to main branch
  Makefile
  includes/macro_bonus.h
Labels: etc :guitar:
